routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout/{id}', '\App\Http\Controllers\Auth\LoginController@logout')->name('user.logout');

Route::resource('about', 'AboutController');
Route::resource('accessibility', 'AccessibilityController');
Route::resource('agenda', 'AgendaController');
Route::resource('print-requests', 'PrintRequestController');
Route::get('artscience','AgendaController@artscience');
Route::get('businessacct','AgendaController@businessacct');
Route::get('compstudies','AgendaController@compstudies');
Route::get('criminology','AgendaController@criminology');
Route::get('education','AgendaController@education');
Route::get('engineeringarchi','AgendaController@engineeringarchi');
Route::get('graduatestudies','AgendaController@graduatestudies');
Route::get('nursing','AgendaController@nursing');
Route::get('law', 'AgendaController@law');




Route::resource('researches','ResearchController');
Route::resource('journals','JournalController');
Route::get('search','ResearchController@search');

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    //
}

app/Models/Accessibility.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Accessibility extends Model
{
    //
    protected $fillable = ['research_id','chapter1','chapter2','chapter3','chapter4','chapter5'];

    public function research(){
        return $this->belongsTo('App\Models\Research');
    }
}

app/Models/Agenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    protected $fillable = [
        'description'
    ];
}

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    protected $fillable = [
        'journal_id', 'fname', 'mname', 'lname', 'type'
    ];

    public function journal(){
        return $this->belongsTo('App\Models\Journal');
    }
}

app/Models/Callnumber.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Callnumber extends Model
{
    protected $fillable = [
        'year', 'location', 'class_name', 'cutter_no'
    ];
}

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $fillable = [
        'name', 'abbrev'
    ];
}

app/Models/Journal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Journal extends Model
{
    protected $fillable = [
        'title', 'year', 'type_id',
        'dept_id', 'status', 'keywords', '_abstract',
        'docs'
    ];

    public function authors(){
        return $this->hasMany('App\Models\Author');
    }
}

app/Models/JournalAgenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class JournalAgenda extends Model
{
    protected $fillable = [
        'journal_id', 'agenda_id'
    ];
}

app/Models/PrintRequest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PrintRequest extends Model
{
    //
    protected $fillable = ['user_id','file','chapter','title','status'];

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Models/Proponent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Proponent extends Model
{
    //
    protected $table = 'proponents';
    protected $fillable = [
        'student_no',
        'fname',
        'mname',
        'lname',
        'isUnderGrad',
        'dept_id',
        'research_id'
    ];

    public function researches(){
        return $this->hasMany('App\Models\ProponentResearch');
    }
}

app/Models/ProponentResearch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProponentResearch extends Model
{
    protected $table = "proponentresearches";

    protected $fillable = ['research_id','proponent_id'];

    public function research(){
        return $this->belongsTo('App\Models\Research');
    }

    public function proponent(){
        return $this->belongsTo('App\Models\Proponent');
    }
}

app/Models/Research.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Research extends Model
{
    protected $fillable = [
        'title', 'status','dept_id', 'type_id', 
        'year', 'no_pages', 'quantity', 'keywords', 
        'call_id', '_abstract', 'chapter1',
        'chapter2', 'chapter3', 'chapter4', 'chapter1'
    ];

    public function proponents(){
        return $this->hasMany('App\Models\ProponentResearch', 'proponent_id');
    }

    public function accessibility(){
        return $this->hasOne('App\Models\Accessibility');
    }
    
}

app/Models/ResearchAgenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ResearchAgenda extends Model
{
    //
}

app/Models/ResearchType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ResearchType extends Model
{
    protected $fillable = [
        'name', 'description'
    ];
}

app/Models/Researcher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Researcher extends Model
{
    protected $fillable = [
        'researcherType_id', 'fname', 'mname', 'lname', 'department_id'
    ];
}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = [
        'name'
    ];
}

app/Models/Status.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    protected $fillable = [
        'name', 'description'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','username', 'password', 'role_id', 'dept_id'
    ];
    
    public function setPasswordAttribute($password){
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function role(){
        return $this->belongsTo('App\Models\Role');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(\Auth::user()->role->id == 4 && \Carbon\Carbon::now(8)->addHour()->format('Y-m-d H:i:s') > \Carbon\Carbon::parse(\Auth::user()->expireOn)->format('Y-m-d H:i:s'))
        {
            return redirect()->route('user.logout',\Auth::user()->id);
        }

        return view('welcome');
    }
}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SearchController extends Controller
{

    public function index()
    {
        return view ('search.index');
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/search/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <div class="row">
<div class="col col-md-5">
    <section class="intro-single">
        <h3>Results for `{{$input}}` </h3>
        @if(count($journals) == 0 && count($results) == 0)
        <h5>No results found</h5>
        @else
        <h5><small>{{ count($journals) }} journal(s) and {{ count($results) }} research(es) found.</small></h5>
        @endif
    </section>  
    <div class="list-group">

    @forelse($journals as $result)
    <a href="{{ route('journals.edit',$result->id) }}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ $result->title }}</h5>
            <p class="text-danger"><b>{{ \Carbon\Carbon::parse($result->year)->format('Y') }}</b></small><br>
        </div>
        <hr>
        Authors:
        @forelse($result->authors as $author)
            <div class="badge badge-light btn-block text-left">{{$author->lname}}, {{$author->fname}} {{$author->mname}}</div>
        @empty
        @endforelse
        <br>
        <br>
        <p class="text-muted">{{substr($result->_abstract,0,298).".."}}</p>
        <p class="text-muted">
        <small>Keywords:</small>   
        @foreach(explode(",",$result->keywords) as $word)
            <span class="badge badge-secondary">{{$word}}</span>
        @endforeach
        </p>
    </a>
    <hr>
    @empty
    @endforelse
    @forelse($results as $result)
    <a href="{{ route('researches.show',$result->id) }}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ $result->title }}</h5>
            <p><b>{{ \Carbon\Carbon::parse($result->year)->format('Y') }}</b></small><br>
        </div>
        <hr>
        Authors:
        @forelse($result->proponents as $proponent)
            <div class="badge badge-light btn-block text-left">{{$proponent->proponent->lname}}, {{$proponent->proponent->fname}} {{$proponent->proponent->mname}}</div>
        @empty
        @endforelse
        <br>
        <br>
        <p class="text-muted">{{substr($result->_abstract,0,298).".."}}</p>
        <p class="text-muted">
        <small>Keywords:</small>   
        @foreach(explode(",",$result->keywords) as $word)
            <span class="badge badge-secondary">{{$word}}</span>
        @endforeach
        </p>
        <!-- <p class="text-muted">
        <small>Proponents:
        @foreach($result->proponents as $proponent)
            {{  $proponent->proponent['fname']}} {{$proponent->proponent['lname']}}
        @endforeach
        </small>   
        </p> -->
    </a>
    <hr>
    @empty
    @endforelse
    </div>
</div>
</div>
</div>
@stop